# Azure DevOps Pipeline for Java Maven Selenium Project

trigger:
  - main

pool:
  # vmImage: 'ubuntu-latest'   # Use hosted agent. If self-hosted, change to: name: 'Default'
  Default

variables:
  MAVEN_OPTS: "-Xmx1024m"

steps:
# Step 1: Checkout code
- checkout: self

# Step 2: Install JDK 21 (manual install)
- script: |
    sudo apt-get update
    sudo apt-get install -y openjdk-21-jdk
    java -version
  displayName: 'Install JDK 21'

# Step 3: Cache Maven packages for faster builds
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: ~/.m2/repository
    restoreKeys: |
      maven | "$(Agent.OS)"

# Step 4: Install Chrome for Selenium tests
- script: chrome --version
  displayName: 'Check Chrome Version'

# Step 5: Build Maven project
- script: mvn clean compile
  displayName: 'Maven Clean & Compile'

# Step 6: Run Selenium tests (headless mode recommended)
- script: mvn test
  displayName: 'Run Selenium Tests'

# Step 7: Package project (optional)
- script: mvn package
  displayName: 'Maven Package'
