trigger:
  - main

pool:
  
  Default  # Use Microsoft-hosted agent

variables:
  LT_USERNAME: 'shivanks'
  LT_ACCESS_KEY: 'LT_V6UEGtFRGiIPH4QcUdNKQv4RIetJjVfXKKIEkrP3Sk15opJ'
  LT_BUILD_NAME: 'Azure_testng_demo'

stages:
- stage: BuildAndTest
  displayName: "Build and Run Tests on LambdaTest"
  jobs:
  - job: BuildAndTestJob
    displayName: "Build & Test Job"
    steps:

      # 1️⃣ Configure LambdaTest connection
      - task: configuration@1
        displayName: "Configure LambdaTest Connection"
        inputs:
          connection: ankit-LT-connection
          # Uncomment if you need a tunnel
          # isTunnelActivate: true
          # tunnelOptions: '{"tunnelName": "MyTunnel"}'

      # 2️⃣ Build Maven project (skip tests)
      - script: |
          mvn clean install -DskipTests
        displayName: "Maven Build"

      # 3️⃣ Run TestNG suite
      - script: |
          mvn clean test 
        displayName: "Run TestNG Suite"

      # 4️⃣ Publish LambdaTest results
      - task: LambdatestResults@1
        displayName: "Publish LambdaTest Results"
        inputs:
          buildName: '$(LT_BUILD_NAME)'
          username: '$(LT_USERNAME)'
          accessKey: '$(LT_ACCESS_KEY)'
