trigger:
  - main
pool:
  name: Default   # Your self-hosted Windows agent pool name
variables:
  MAVEN_OPTS: "-Xmx1024m"
steps:
- checkout: self

# Step 1: Install Chocolatey (if not already installed)
- powershell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; 
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; 
    iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
  displayName: 'Install Chocolatey'

# Step 2: Install JDK 21 using Chocolatey
- powershell: |
    choco install openjdk21 -y
    java -version
  displayName: 'Install JDK 21'

# Step 3: Cache Maven dependencies
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | **/pom.xml'
    path: '$(USERPROFILE)\.m2\repository'
    restoreKeys: |
      maven | "$(Agent.OS)"

# Step 4: Install Google Chrome and ChromeDriver using PowerShell
- powershell: |
    # (your previous Chrome and ChromeDriver installation script here)
  displayName: 'Install Chrome and ChromeDriver'

# Step 5: Build Maven project
- script: mvn clean compile
  displayName: 'Maven Clean & Compile'

# Step 6: Run Selenium tests (headless mode recommended)
- script: mvn test
  displayName: 'Run Selenium Tests'

# Step 7: Package project (optional)
- script: mvn package
  displayName: 'Maven Package'
